name = "ZigGet"
uuid = "64448d04-f91e-4661-b706-50d7101e37ac"
authors = ["dimsinel <dimsinel@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
